name: Build and Push Docker Image
on:
  push:
    tags:
      - "*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Docker tag
        id: set_tag
        run: echo "::set-output name=tag::${{ github.ref }}"

      - name: Extract tag name
        id: extract_tag
        run: |
          tag_name=${{ steps.set_tag.outputs.tag }}
          if [[ $tag_name == refs/tags/* ]]; then
            tag_name=${tag_name#refs/tags/}
          fi
          echo "::set-output name=tag_name::${tag_name}"

      - name: Login Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile.amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: registry.digitalocean.com/tht/quan-ly-tau-thuy-vsico:${{ steps.extract_tag.outputs.tag_name }}

      - name: Set up Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      - name: Upgrade/Install vex-reactjs-frontend chart
        run: |
          helm upgrade --install --set image.tag=${{ steps.extract_tag.outputs.tag_name }} quan-ly-tau ./helmchart --namespace quan-ly-tau
